spring:
  application:
    name: ffib-backend

  profiles:
    active: local

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

logging:
  level:
    root: INFO

info:
  app:
    name: FFIB Backend
    version: 1.0.0
    description: Football Federation Information Backend API

springdoc:
  api-docs:
    enabled: true

  swagger-ui:
    enabled: true
    path: /swagger-ui

  show-actuator: false